"""Add user relationships to TaskSchedule and TaskLog

Revision ID: aed7496f8061
Revises: cd4002fd5282
Create Date: 2025-05-16 22:22:10.402301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aed7496f8061'
down_revision: Union[str, None] = 'cd4002fd5282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_log', sa.Column('task_id', sa.Integer(), nullable=True))
    op.alter_column('task_log', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_foreign_key(None, 'task_log', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_log', type_='foreignkey')
    op.alter_column('task_log', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('task_log', 'task_id')
    # ### end Alembic commands ###
