"""Add user_id relationships

Revision ID: cd4002fd5282
Revises: 
Create Date: 2025-05-16 01:38:23.973140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd4002fd5282'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_log', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('task_log', 'remarks',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.create_foreign_key(None, 'task_log', 'users', ['user_id'], ['id'])
    op.add_column('task_schedule', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('task_schedule', 'remarks',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.create_foreign_key(None, 'task_schedule', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_schedule', type_='foreignkey')
    op.alter_column('task_schedule', 'remarks',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('task_schedule', 'user_id')
    op.drop_constraint(None, 'task_log', type_='foreignkey')
    op.alter_column('task_log', 'remarks',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('task_log', 'user_id')
    # ### end Alembic commands ###
